Updating Kubernetes network policy
bcgov/ocp-sso pull request #187
Opened 2021-02-26 21:29 UTC by nvunnamm

2021-02-26 21:37 UTC, patricksimonian requested changes

2021-02-26 21:37 UTC, patricksimonian commented on README.md
>  oc -n 6d70e7-tools process -f openshift/nsp.yaml -p 'NAMESPACE=6d70e7-tools' | oc -n 6d70e7-tools create -f -
we probably want to remove or atleast highlight you WILL not need to run aporeto policies.

2021-02-26 21:37 UTC, patricksimonian commented on openshift/knp.yaml
> +    value: ""
new line

2021-03-03 19:15 UTC, patricksimonian approved these changes
have these changes been tested in sandbox with zero aporeto based policies?

2021-03-03 21:04 UTC, nvunnamm commented
> have these changes been tested in sandbox with zero aporeto based policies?

2021-03-03 21:07 UTC, nvunnamm commented
closed this unexpectedly.. Reopening it.
The changes which I made are tested in sandbox.. but we had to add 2 aporeto based policies as per the guide.

2021-04-28 02:57 UTC, merged